apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: fhhee6fd6-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-qe-jsmid/fhhee6fd6-java-quarkus-gitops